<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

 // Add custom 404 page body class to site-inner.

add_filter('genesis_attr_site-inner', 'rubesreview_add_body_class');
function rubesreview_add_body_class($attributes) {
	$attributes['class'] .= ' rubes-404-page';
	return $attributes;
}

// Remove default loop.
remove_action( 'genesis_loop', 'genesis_do_loop' );
add_action( 'genesis_loop', 'genesis_404' );
/**
 * This function outputs a 404 "Not Found" error message.
 *
 * @since 1.6
 */
function genesis_404() {

	genesis_markup( array(
		'open' => '<article class="entry rubes-404-page">',
		'context' => 'entry-404',
	) );

		printf( '<h1 class="entry-title">%s</h1>', apply_filters( 'genesis_404_entry_title', __( 'Sorry, that URL resulted in a \'Page Not Found\' - Error 404.', 'genesis' ) ) );
		echo '<div class="entry-content">';

			if ( genesis_html5() ) :

				echo apply_filters( 'genesis_404_entry_content', '<p>' . sprintf( __( 'The page you are looking for no longer exists. You can return back to the <a href="%s">front page</a> and see if you can find what you are looking for. Or, you can try finding it by using the search form below. At the bottom of this page is a <a href="#rubes-sitemap">Sitemap</a> listing all the different pages on our site. Check to see if any of them are close to what you were looking for.', 'genesis' ), trailingslashit( home_url() ) ) . '</p>' );

				get_search_form();

			else :
	?>

			<p><?php printf( __( 'The page you are looking for no longer exists. Perhaps you can return back to the site\'s <a href="%s">homepage</a> and see if you can find what you are looking for. Or, you can try finding it with the information below.', 'genesis' ), trailingslashit( home_url() ) ); ?></p>



	<?php
			endif;

			printf('<a id="rubes-sitemap"></a>');
			if ( genesis_a11y( '404-page' ) ) {
				echo '<h2>' . __( 'Sitemap', 'genesis' ) . '</h2>';
				genesis_sitemap( 'h3' );
			} else {
				genesis_sitemap( 'h4' );
			}

		echo '</div>';

	genesis_markup( array(
		'close' => '</article>',
		'context' => 'entry-404',
	) );

}

genesis();
