<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

 // Add spotlight posts class to the head.
add_filter( 'genesis_attr_structural-wrap', 'rubes_my_custom_class' );  
function rubes_my_custom_class( $attributes ) {
	if ( is_single( ) )
		$attributes['class'] = $attributes['class'] . ' spotlight-content';
		return $attributes;
}

// Force Content/Sidebar layout.
add_filter( 'genesis_site_layout', '__genesis_return_content_sidebar' );

// Add the BB template header to single post pages
add_action('genesis_after_header', 'add_bb_image');
function add_bb_image(){
	echo do_shortcode('[fl_builder_insert_layout id="1969"]');
}

genesis();
