<?php
if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_malpractice-fields',
		'title' => 'Malpractice fields',
		'fields' => array (
			array (
				'key' => 'field_5a30822c481bc',
				'label' => 'malp-field01',
				'name' => 'malp-field01',
				'type' => 'text',
				'instructions' => 'With which malpractice company are you associated?',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => 'With which malpractice company are you associated?',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5a3082abf6429',
				'label' => 'malp-field02',
				'name' => 'malp-field02',
				'type' => 'number',
				'instructions' => 'How would you rate the contact person, from the malpractice company, with whom you are associated.',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => 1,
				'max' => 5,
				'step' => '',
			),
			array (
				'key' => 'field_5a3082edf642a',
				'label' => 'malp-field03',
				'name' => 'malp-field03',
				'type' => 'number',
				'instructions' => 'Being polite.',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => 1,
				'max' => 5,
				'step' => '',
			),
			array (
				'key' => 'field_5a308303f642b',
				'label' => 'malp-field04',
				'name' => 'malp-field04',
				'type' => 'number',
				'instructions' => 'Being professional, in communicating with you. ',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => 1,
				'max' => 5,
				'step' => '',
			),
			array (
				'key' => 'field_5a30831ef642c',
				'label' => 'malp-field05',
				'name' => 'malp-field05',
				'type' => 'number',
				'instructions' => 'Being knowledgeable, about the medical malpractice field and company they represent.',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => 1,
				'max' => 5,
				'step' => '',
			),
			array (
				'key' => 'field_5a308333f642d',
				'label' => 'malp-field06',
				'name' => 'malp-field06',
				'type' => 'number',
				'instructions' => 'Being given a choice of insurance companies to choose from?',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => 1,
				'max' => 5,
				'step' => '',
			),
			array (
				'key' => 'field_5a30838ff642e',
				'label' => 'malp-field07',
				'name' => 'malp-field07',
				'type' => 'number',
				'instructions' => 'Liability and Term limits, of which there are several, depending on your practice.',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => 1,
				'max' => 5,
				'step' => '',
			),
			array (
				'key' => 'field_5a30839ff642f',
				'label' => 'malp-field08',
				'name' => 'malp-field08',
				'type' => 'number',
				'instructions' => 'Information explained regarding liability and term limits to you.',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => 1,
				'max' => 5,
				'step' => '',
			),
			array (
				'key' => 'field_5a3083b0f6430',
				'label' => 'malp-field09',
				'name' => 'malp-field09',
				'type' => 'number',
				'instructions' => 'Their explanation was easy to understand.	',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => 1,
				'max' => 5,
				'step' => '',
			),
			array (
				'key' => 'field_5a3083c7f6431',
				'label' => 'malp-field10',
				'name' => 'malp-field10',
				'type' => 'number',
				'instructions' => 'Payment options given and explained.',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => 1,
				'max' => 5,
				'step' => '',
			),
			array (
				'key' => 'field_5a3083def6432',
				'label' => 'malp-field11',
				'name' => 'malp-field11',
				'type' => 'number',
				'instructions' => 'Insurance premium jacket provided by email, fax, or hard copy- mail.',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => 1,
				'max' => 5,
				'step' => '',
			),
			array (
				'key' => 'field_5a3083f2f6433',
				'label' => 'malp-field12',
				'name' => 'malp-field12',
				'type' => 'number',
				'instructions' => 'Reporting information given with contact names and numbers. ',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => 1,
				'max' => 5,
				'step' => '',
			),
			array (
				'key' => 'field_5a308cfde4172',
				'label' => 'MALP Average Rating',
				'name' => 'malp_average_rating',
				'type' => 'number',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'min' => '',
				'max' => '',
				'step' => '',
			),
			array (
				'key' => 'field_5a308e126caef',
				'label' => 'MALP Additional Comments',
				'name' => 'malp_additional_comments',
				'type' => 'textarea',
				'default_value' => '',
				'placeholder' => '',
				'maxlength' => 1000,
				'rows' => 5,
				'formatting' => 'br',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'evaluation',
					'order_no' => 0,
					'group_no' => 0,
				),
				array (
					'param' => 'taxonomy',
					'operator' => '==',
					'value' => '6',
					'order_no' => 1,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
			),
		),
		'menu_order' => 0,
	));
}
